# Project_1. Curate a Dataset

In [1]:
g = open('reviews.txt', 'r') # What we know
reviews = list(map(lambda x:x[:-1], g.readlines()))
g.close()

g = open('labels.txt', 'r') # What we Want to know!
labels = list(map(lambda x:x[:-1].upper(), g.readlines()))
g.close()

In [2]:
len(reviews)

25000

In [3]:
reviews[0]

'bromwell high is a cartoon comedy . it ran at the same time as some other programs about school life  such as  teachers  . my   years in the teaching profession lead me to believe that bromwell high  s satire is much closer to reality than is  teachers  . the scramble to survive financially  the insightful students who can see right through their pathetic teachers  pomp  the pettiness of the whole situation  all remind me of the schools i knew and their students . when i saw the episode in which a student repeatedly tried to burn down the school  i immediately recalled . . . . . . . . . at . . . . . . . . . . high . a classic line inspector i  m here to sack one of your teachers . student welcome to bromwell high . i expect that many adults of my age think that bromwell high is far fetched . what a pity that it isn  t   '

In [4]:
labels[0]

'POSITIVE'

In [5]:
def pretty_print_revie_and_label(i):
    print(labels[i] + '\t:\t' + reviews[i][:80] + '...')

In [6]:
print('labels.txt \t:\t revies.txt\n')
pretty_print_revie_and_label(4563)
pretty_print_revie_and_label(1235)
pretty_print_revie_and_label(345)

labels.txt 	:	 revies.txt

NEGATIVE	:	as always this is an inaccurate picture of the homeless . tv told a lot of lies ...
NEGATIVE	:	this is a good example of how not to make a film .  br    br   there is very lit...
NEGATIVE	:	i have read several good reviews that have defended and critised the various asp...


# Project_2. Quick Theory Validation

In [7]:
from collections import Counter
import numpy as np

In [8]:
positive_counts = Counter()
negative_counts = Counter()
total_counts = Counter()

In [9]:
for i in range(len(reviews)):
    if labels[i] == 'POSITIVE':
        for word in reviews[i].split(' '):
            positive_counts[word] += 1
            total_counts[word] += 1
    else:
        for word in reviews[i].split(' '):
            negative_counts[word] += 1
            total_counts[word] += 1

In [10]:
positive_counts.most_common()

[('', 550468),
 ('the', 173324),
 ('.', 159654),
 ('and', 89722),
 ('a', 83688),
 ('of', 76855),
 ('to', 66746),
 ('is', 57245),
 ('in', 50215),
 ('br', 49235),
 ('it', 48025),
 ('i', 40743),
 ('that', 35630),
 ('this', 35080),
 ('s', 33815),
 ('as', 26308),
 ('with', 23247),
 ('for', 22416),
 ('was', 21917),
 ('film', 20937),
 ('but', 20822),
 ('movie', 19074),
 ('his', 17227),
 ('on', 17008),
 ('you', 16681),
 ('he', 16282),
 ('are', 14807),
 ('not', 14272),
 ('t', 13720),
 ('one', 13655),
 ('have', 12587),
 ('be', 12416),
 ('by', 11997),
 ('all', 11942),
 ('who', 11464),
 ('an', 11294),
 ('at', 11234),
 ('from', 10767),
 ('her', 10474),
 ('they', 9895),
 ('has', 9186),
 ('so', 9154),
 ('like', 9038),
 ('about', 8313),
 ('very', 8305),
 ('out', 8134),
 ('there', 8057),
 ('she', 7779),
 ('what', 7737),
 ('or', 7732),
 ('good', 7720),
 ('more', 7521),
 ('when', 7456),
 ('some', 7441),
 ('if', 7285),
 ('just', 7152),
 ('can', 7001),
 ('story', 6780),
 ('time', 6515),
 ('my', 6488),
 ('g

In [11]:
negative_counts.most_common()

[('', 561462),
 ('.', 167538),
 ('the', 163389),
 ('a', 79321),
 ('and', 74385),
 ('of', 69009),
 ('to', 68974),
 ('br', 52637),
 ('is', 50083),
 ('it', 48327),
 ('i', 46880),
 ('in', 43753),
 ('this', 40920),
 ('that', 37615),
 ('s', 31546),
 ('was', 26291),
 ('movie', 24965),
 ('for', 21927),
 ('but', 21781),
 ('with', 20878),
 ('as', 20625),
 ('t', 20361),
 ('film', 19218),
 ('you', 17549),
 ('on', 17192),
 ('not', 16354),
 ('have', 15144),
 ('are', 14623),
 ('be', 14541),
 ('he', 13856),
 ('one', 13134),
 ('they', 13011),
 ('at', 12279),
 ('his', 12147),
 ('all', 12036),
 ('so', 11463),
 ('like', 11238),
 ('there', 10775),
 ('just', 10619),
 ('by', 10549),
 ('or', 10272),
 ('an', 10266),
 ('who', 9969),
 ('from', 9731),
 ('if', 9518),
 ('about', 9061),
 ('out', 8979),
 ('what', 8422),
 ('some', 8306),
 ('no', 8143),
 ('her', 7947),
 ('even', 7687),
 ('can', 7653),
 ('has', 7604),
 ('good', 7423),
 ('bad', 7401),
 ('would', 7036),
 ('up', 6970),
 ('only', 6781),
 ('more', 6730),
 ('

In [12]:
pos_neg_ratios = Counter()

for term, cnt in list(total_counts.most_common()):
    if cnt > 100:
        pos_neg_ratio = positive_counts[term] / (negative_counts[term] + 1)
        pos_neg_ratios[term] = pos_neg_ratio
    
for word, ratio in list(pos_neg_ratios.most_common()):
    if ratio > 1:
        pos_neg_ratios[word] = np.log(ratio)
    else:
        pos_neg_ratios[word] = -np.log(1 / (ratio + 0.01))

In [13]:
pos_neg_ratios.most_common()

[('edie', 4.6913478822291435),
 ('paulie', 4.0775374439057197),
 ('felix', 3.1527360223636558),
 ('polanski', 2.8233610476132043),
 ('matthau', 2.8067217286092401),
 ('victoria', 2.6810215287142909),
 ('mildred', 2.6026896854443837),
 ('gandhi', 2.5389738710582761),
 ('flawless', 2.451005098112319),
 ('superbly', 2.2600254785752498),
 ('perfection', 2.1594842493533721),
 ('astaire', 2.1400661634962708),
 ('captures', 2.0386195471595809),
 ('voight', 2.0301704926730531),
 ('wonderfully', 2.0218960560332353),
 ('powell', 1.9783454248084671),
 ('brosnan', 1.9547990964725592),
 ('lily', 1.9203768470501485),
 ('bakshi', 1.9029851043382795),
 ('lincoln', 1.9014583864844796),
 ('refreshing', 1.8551812956655511),
 ('breathtaking', 1.8481124057791867),
 ('bourne', 1.8478489358790986),
 ('lemmon', 1.8458266904983307),
 ('delightful', 1.8002701588959635),
 ('flynn', 1.7996646487351682),
 ('andrews', 1.7764919970972666),
 ('homer', 1.7692866133759964),
 ('beautifully', 1.7626953362841438),
 ('socc

In [14]:
list(reversed(pos_neg_ratios.most_common()))[:30]

[('boll', -4.0778152602708904),
 ('uwe', -3.9218753018711578),
 ('seagal', -3.3202501058581921),
 ('unwatchable', -3.0269848170580955),
 ('stinker', -2.9876839403711624),
 ('mst', -2.7753833211707968),
 ('incoherent', -2.7641396677532537),
 ('unfunny', -2.5545257844967644),
 ('waste', -2.4907515123361046),
 ('blah', -2.4475792789485005),
 ('horrid', -2.3715779644809971),
 ('pointless', -2.3451073877136341),
 ('atrocious', -2.3187369339642556),
 ('redeeming', -2.2667790015910296),
 ('prom', -2.2601040980178784),
 ('drivel', -2.2476029585766928),
 ('lousy', -2.2118080125207054),
 ('worst', -2.1930856334332267),
 ('laughable', -2.172468615469592),
 ('awful', -2.1385076866397488),
 ('poorly', -2.1326133844207011),
 ('wasting', -2.1178155545614512),
 ('remotely', -2.111046881095167),
 ('existent', -2.0024805005437076),
 ('boredom', -1.9241486572738005),
 ('miserably', -1.9216610938019989),
 ('sucks', -1.9166645809588516),
 ('uninspired', -1.9131499212248517),
 ('lame', -1.9117232884159072),

# Project_3. Transforming Text into Numbers
**_Creating the Input/Output Data_**

In [15]:
vocab = set(total_counts.keys())
vocab_size = len(vocab)
print(vocab_size)

74074


In [16]:
list(vocab)[:30]

['',
 'complains',
 'subordination',
 'boooring',
 'cookies',
 'dex',
 'lotion',
 'r',
 'spartan',
 'falsifies',
 'reworked',
 'dodger',
 'tracys',
 'rang',
 'engrish',
 'niles',
 'advertisement',
 'inflaming',
 'costars',
 'bonk',
 'any',
 'christensen',
 'crib',
 'enjoying',
 'adjuster',
 'two',
 'consist',
 'egbert',
 'alright',
 'moneymaker']

In [17]:
layer_0 = np.zeros((1, vocab_size))
layer_0

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [18]:
word2index = {}

for idx, word in enumerate(vocab):
    word2index[word] = idx

word2index

{'': 0,
 'complains': 1,
 'subordination': 2,
 'boooring': 3,
 'cookies': 4,
 'dex': 5,
 'lotion': 6,
 'r': 7,
 'spartan': 8,
 'falsifies': 9,
 'reworked': 10,
 'dodger': 11,
 'tracys': 12,
 'rang': 13,
 'engrish': 14,
 'niles': 15,
 'advertisement': 16,
 'inflaming': 17,
 'costars': 18,
 'bonk': 19,
 'any': 20,
 'christensen': 21,
 'crib': 22,
 'enjoying': 23,
 'adjuster': 24,
 'two': 25,
 'consist': 26,
 'egbert': 27,
 'alright': 28,
 'moneymaker': 29,
 'terminated': 30,
 'smittened': 31,
 'recap': 32,
 'syberberg': 33,
 'painer': 34,
 'victims': 35,
 'clubbing': 36,
 'anchorwoman': 37,
 'debucourt': 38,
 'outing': 39,
 'applebloom': 40,
 'yetis': 41,
 'argentina': 42,
 'kmadden': 43,
 'chasse': 44,
 'tournaments': 45,
 'coronel': 46,
 'pliskin': 47,
 'tastey': 48,
 'insanity': 49,
 'looonnnggg': 50,
 'changruputra': 51,
 'universality': 52,
 'evenings': 53,
 'khans': 54,
 'nsync': 55,
 'mapple': 56,
 'unlucky': 57,
 'breakdown': 58,
 'adjustment': 59,
 'encounter': 60,
 'instructors

In [19]:
def update_input_data(review):
    global layer_0 
    
    # clear out previous state, reset the layer to be all 0s
    layer_0 *= 0
    for word in review.split(' '):
        layer_0[0][word2index[word]] += 1
        
update_input_data(reviews[0])

In [20]:
layer_0

array([[ 18.,   0.,   0., ...,   0.,   0.,   0.]])

In [21]:
def get_target_for_label(label):
    if label == 'POSITIVE':
        return 1
    else:
        return 0

# Project_4. Build a Neural Network

In [22]:
import sys
import time
import numpy as np

class SentimentNetwork_1:
    def __init__(self, reviews, labels, hidden_nodes = 10, learning_rate = 0.1):
        
        # set our random number generator
        np.random.seed(1)
        
        self.pre_process_data(reviews, labels)
        self.init_network(len(self.review_vocab), hidden_nodes, 1, learning_rate)
        
    def pre_process_data(self, reviews, labels):
        review_vocab = set()
        for review in reviews:
            for word in review.split(' '):
                review_vocab.add(word)
        self.review_vocab = list(review_vocab)
        
        label_vocab = set()
        for label in labels:
            for word in label.split(' '):
                label_vocab.add(word)
        self.label_vocab = list(label_vocab)
        
        self.word2index = {}
        for idx, word in enumerate(review_vocab):
            self.word2index[word] = idx
        
        self.label2index = {}
        for idx, label in enumerate(label_vocab):
            self.label2index[label] = idx
        
        
    def init_network(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        # Set number of nodes in input, hidden, and output layers.
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes
        
        # Initialize the weights
        self.weights_0_1 = np.zeros((self.input_nodes, self.hidden_nodes))
        
        self.weights_1_2 = np.random.normal(0.0, self.output_nodes**-0.5, (self.hidden_nodes, self.output_nodes))
        
        self.lr = learning_rate
        
        self.layer_0 = np.zeros((1, input_nodes))
        
    def update_input_data(self, review):
        self.layer_0 *= 0 
        
        for word in review.split(' '):
            if (word in self.word2index.keys()):
                self.layer_0[0][self.word2index[word]] += 1
            
    def get_target_for_label(self, label):
        if label == 'POSITIVE':
            return 1
        else:
            return 0
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def sigmoid_output_2_derivative(self, output):
        return output * (1 - output)
    
    def train(self, training_reviews, training_labels):
        assert(len(training_reviews) == len(training_labels))
        
        correct_so_far = 0
        
        start = time.time()
        
        for i in range(len(training_reviews)):
            review = training_reviews[i]
            label = training_labels[i]
            
            ### Implement the forward pass here ###
            ## Forward pass
            
            # Input layer
            self.update_input_data(review)
            
            # Hidden layer
            hidden_layer = np.dot(self.layer_0, self.weights_0_1)
                        
            # Output layer
            output = self.sigmoid(np.dot(hidden_layer, self.weights_1_2))
            
            ### Implement the backward pass here ###
            ## Backward pass
            
            # Output Error
            output_error = self.get_target_for_label(label) - output
            output_error_d = output_error*self.sigmoid_output_2_derivative(output)
            
            # Backpropagated Error
            hidden_error = np.dot(output_error_d, self.weights_1_2.T)
            hidden_error_d = hidden_error
            
            # Updates the weights
            self.weights_1_2 += self.lr*np.dot(hidden_layer.T, output_error_d)
            self.weights_0_1 += self.lr*np.dot(self.layer_0.T, hidden_error_d)
            
            if np.abs(output_error) < 0.5:
                correct_so_far += 1
            
            review_per_second = i / float(time.time() - start)

            sys.stdout.write('\rProcess:' + str(100*i/float(len(training_reviews)))[:4] + \
                             '% Speed(reviews/sec):' + str(review_per_second)[:5] + \
                            '% #Correct:' + str(correct_so_far) + ' #Trained:' + str(i+1) \
                            + ' Training Accuracy:' + str(correct_so_far*100/float(i+1))[:4])
            if i % 2500 == 0:
                print(" ")
                
    def test(self, testing_reviews, testing_labels):
        correct = 0
        
        start = time.time()
        
        for i in range(len(testing_reviews)):
            pred = self.run(testing_reviews[i])
            if (pred == testing_labels[i]):
                correct += 1
                
            review_per_second = i / float(time.time() - start)
            
            sys.stdout.write('\rProcess:' + str(100*i/float(len(testing_reviews)))[:4] + \
                             '% Speed(reviews/sec):' + str(review_per_second)[:5] + \
                            '% #Correct:' + str(correct) + ' #Tested:' + str(i+1) \
                            + ' Testing Accuracy:' + str(correct*100/float(i+1))[:4])
            
        
    def run(self, review):
        # Input layer
        self.update_input_data(review.lower())
        
        # Hidden layer
        hidden_layer = np.dot(self.layer_0, self.weights_0_1)
        
        # Output layer
        output = self.sigmoid(np.dot(hidden_layer, self.weights_1_2))
        
        if output[0] > 0.5:
            return 'POSITIVE'
        else:
            return 'NEGATIVE'
                

In [23]:
mlp_1 = SentimentNetwork_1(reviews[:-1000], labels[:-1000], learning_rate=0.01)

In [24]:
# evaluate our model before training (just show how horrible it is)
mlp_1.test(reviews[-1000:], labels[-1000:])

Process:99.9% Speed(reviews/sec):850.2% #Correct:500 #Tested:1000 Testing Accuracy:50.0

In [25]:
# Train the Network
mlp_1.train(reviews[:-1000], labels[:-1000])

Process:0.0% Speed(reviews/sec):0.0% #Correct:0 #Trained:1 Training Accuracy:0.0 
Process:10.4% Speed(reviews/sec):166.0% #Correct:1247 #Trained:2501 Training Accuracy:49.8 
Process:20.8% Speed(reviews/sec):171.9% #Correct:2497 #Trained:5001 Training Accuracy:49.9 
Process:31.2% Speed(reviews/sec):171.2% #Correct:3747 #Trained:7501 Training Accuracy:49.9 
Process:41.6% Speed(reviews/sec):170.2% #Correct:4997 #Trained:10001 Training Accuracy:49.9 
Process:52.0% Speed(reviews/sec):170.5% #Correct:6247 #Trained:12501 Training Accuracy:49.9 
Process:62.5% Speed(reviews/sec):169.6% #Correct:7492 #Trained:15001 Training Accuracy:49.9 
Process:72.9% Speed(reviews/sec):169.2% #Correct:8742 #Trained:17501 Training Accuracy:49.9 
Process:83.3% Speed(reviews/sec):167.1% #Correct:9992 #Trained:20001 Training Accuracy:49.9 
Process:93.7% Speed(reviews/sec):166.5% #Correct:11242 #Trained:22501 Training Accuracy:49.9 
Process:99.9% Speed(reviews/sec):163.7% #Correct:11991 #Trained:24000 Training Accu

# Project_5. Reducing Noise in our Input Data

In [26]:
import sys
import time
import numpy as np

class SentimentNetwork_2:
    def __init__(self, reviews, labels, hidden_nodes = 10, learning_rate = 0.1):
        
        # set our random number generator
        np.random.seed(1)
        
        self.pre_process_data(reviews, labels)
        self.init_network(len(self.review_vocab), hidden_nodes, 1, learning_rate)
        
    def pre_process_data(self, reviews, labels):
        review_vocab = set()
        for review in reviews:
            for word in review.split(' '):
                review_vocab.add(word)
        self.review_vocab = list(review_vocab)
        
        label_vocab = set()
        for label in labels:
            for word in label.split(' '):
                label_vocab.add(word)
        self.label_vocab = list(label_vocab)
        
        self.word2index = {}
        for idx, word in enumerate(review_vocab):
            self.word2index[word] = idx
        
        self.label2index = {}
        for idx, label in enumerate(label_vocab):
            self.label2index[label] = idx
        
        
    def init_network(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        # Set number of nodes in input, hidden, and output layers.
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes
        
        # Initialize the weights
        self.weights_0_1 = np.zeros((self.input_nodes, self.hidden_nodes))
        
        self.weights_1_2 = np.random.normal(0.0, self.output_nodes**-0.5, (self.hidden_nodes, self.output_nodes))
        
        self.lr = learning_rate
        
        self.layer_0 = np.zeros((1, input_nodes))
        
    def update_input_data(self, review):
        self.layer_0 *= 0 
        
        for word in review.split(' '):
            if (word in self.word2index.keys()):
                self.layer_0[0][self.word2index[word]] = 1  ### Modify to reduce noise in Input data
            
    def get_target_for_label(self, label):
        if label == 'POSITIVE':
            return 1
        else:
            return 0
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def sigmoid_output_2_derivative(self, output):
        return output * (1 - output)
    
    def train(self, training_reviews, training_labels):
        assert(len(training_reviews) == len(training_labels))
        
        correct_so_far = 0
        
        start = time.time()
        
        for i in range(len(training_reviews)):
            review = training_reviews[i]
            label = training_labels[i]
            
            ### Implement the forward pass here ###
            ## Forward pass
            
            # Input layer
            self.update_input_data(review)
            
            # Hidden layer
            hidden_layer = np.dot(self.layer_0, self.weights_0_1)
                        
            # Output layer
            output = self.sigmoid(np.dot(hidden_layer, self.weights_1_2))
            
            ### Implement the backward pass here ###
            ## Backward pass
            
            # Output Error
            output_error = self.get_target_for_label(label) - output
            output_error_d = output_error*self.sigmoid_output_2_derivative(output)
            
            # Backpropagated Error
            hidden_error = np.dot(output_error_d, self.weights_1_2.T)
            hidden_error_d = hidden_error
            
            # Updates the weights
            self.weights_1_2 += self.lr*np.dot(hidden_layer.T, output_error_d)
            self.weights_0_1 += self.lr*np.dot(self.layer_0.T, hidden_error_d)
            
            if np.abs(output_error) < 0.5:
                correct_so_far += 1
            
            review_per_second = i / float(time.time() - start)

            sys.stdout.write('\rProcess:' + str(100*i/float(len(training_reviews)))[:4] + \
                             '% Speed(reviews/sec):' + str(review_per_second)[:5] + \
                            '% #Correct:' + str(correct_so_far) + ' #Trained:' + str(i+1) \
                            + ' Training Accuracy:' + str(correct_so_far*100/float(i+1))[:4])
            if i % 2500 == 0:
                print(" ")
                
    def test(self, testing_reviews, testing_labels):
        correct = 0
        
        start = time.time()
        
        for i in range(len(testing_reviews)):
            pred = self.run(testing_reviews[i])
            if (pred == testing_labels[i]):
                correct += 1
                
            review_per_second = i / float(time.time() - start)
            
            sys.stdout.write('\rProcess:' + str(100*i/float(len(testing_reviews)))[:4] + \
                             '% Speed(reviews/sec):' + str(review_per_second)[:5] + \
                            '% #Correct:' + str(correct) + ' #Tested:' + str(i+1) \
                            + ' Testing Accuracy:' + str(correct*100/float(i+1))[:4])
            
        
    def run(self, review):
        # Input layer
        self.update_input_data(review.lower())
        
        # Hidden layer
        hidden_layer = np.dot(self.layer_0, self.weights_0_1)
        
        # Output layer
        output = self.sigmoid(np.dot(hidden_layer, self.weights_1_2))
        
        if output[0] > 0.5:
            return 'POSITIVE'
        else:
            return 'NEGATIVE'
                

In [27]:
mlp_2 = SentimentNetwork_2(reviews[:-1000], labels[:-1000], learning_rate=0.1)

In [28]:
mlp_2.train(reviews[:-1000], labels[:-1000])

Process:0.0% Speed(reviews/sec):0.0% #Correct:0 #Trained:1 Training Accuracy:0.0 
Process:10.4% Speed(reviews/sec):128.1% #Correct:1814 #Trained:2501 Training Accuracy:72.5 
Process:20.8% Speed(reviews/sec):146.8% #Correct:3811 #Trained:5001 Training Accuracy:76.2 
Process:31.2% Speed(reviews/sec):157.4% #Correct:5877 #Trained:7501 Training Accuracy:78.3 
Process:41.6% Speed(reviews/sec):161.5% #Correct:8018 #Trained:10001 Training Accuracy:80.1 
Process:52.0% Speed(reviews/sec):162.8% #Correct:10158 #Trained:12501 Training Accuracy:81.2 
Process:62.5% Speed(reviews/sec):165.4% #Correct:12292 #Trained:15001 Training Accuracy:81.9 
Process:72.9% Speed(reviews/sec):166.3% #Correct:14416 #Trained:17501 Training Accuracy:82.3 
Process:83.3% Speed(reviews/sec):163.5% #Correct:16588 #Trained:20001 Training Accuracy:82.9 
Process:93.7% Speed(reviews/sec):164.4% #Correct:18768 #Trained:22501 Training Accuracy:83.4 
Process:99.9% Speed(reviews/sec):165.1% #Correct:20097 #Trained:24000 Training 

In [29]:
# evaluate our model
mlp_2.test(reviews[-1000:], labels[-1000:])

Process:99.9% Speed(reviews/sec):1001.% #Correct:856 #Tested:1000 Testing Accuracy:85.6

In [31]:
mlp_2.weights_0_1.shape

(72810, 10)

In [32]:
mlp_2.weights_0_1[0]

array([ 0.00341835, -0.00128741, -0.00111151, -0.00225801,  0.0018212 ,
       -0.00484347,  0.00367186, -0.00160192,  0.0006714 , -0.00052479])

In [33]:
mlp_2.weights_1_2.shape

(10, 1)

In [35]:
mlp_2.weights_1_2

array([[ 0.47427975],
       [-0.17862192],
       [-0.15421669],
       [-0.31328762],
       [ 0.25268353],
       [-0.67200808],
       [ 0.50945379],
       [-0.22225878],
       [ 0.0931537 ],
       [-0.07281168]])

# Project_6. Making our Network more Efficient

In [36]:
layer_ex = np.zeros((1, 10))

In [37]:
layer_ex

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [38]:
layer_ex[0][4] = 1
layer_ex[0][9] = 1

In [39]:
layer_ex

array([[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]])

In [40]:
weights = np.random.randn(10, 5)

In [41]:
layer_ex.dot(weights)

array([[-0.10503756,  0.44222989,  0.24392938, -0.55961832,  0.21389503]])

In [42]:
indices = [4,9]

In [43]:
layer_ex_1 = np.zeros((1,5))

In [44]:
for idx in indices:
    layer_ex_1 += weights[idx]

In [45]:
layer_ex_1

array([[-0.10503756,  0.44222989,  0.24392938, -0.55961832,  0.21389503]])

In [46]:
import sys
import time
import numpy as np

class SentimentNetwork_3:
    def __init__(self, reviews, labels, hidden_nodes = 10, learning_rate = 0.1):
        
        # set our random number generator
        np.random.seed(1)
        
        self.pre_process_data(reviews, labels)
        self.init_network(len(self.review_vocab), hidden_nodes, 1, learning_rate)
        
    def pre_process_data(self, reviews, labels):
        review_vocab = set()
        for review in reviews:
            for word in review.split(' '):
                review_vocab.add(word)
        self.review_vocab = list(review_vocab)
        
        label_vocab = set()
        for label in labels:
            for word in label.split(' '):
                label_vocab.add(word)
        self.label_vocab = list(label_vocab)
        
        self.word2index = {}
        for idx, word in enumerate(review_vocab):
            self.word2index[word] = idx
        
        self.label2index = {}
        for idx, label in enumerate(label_vocab):
            self.label2index[label] = idx
        
        
    def init_network(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        # Set number of nodes in input, hidden, and output layers.
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes
        
        # Initialize the weights
        self.weights_0_1 = np.zeros((self.input_nodes, self.hidden_nodes))
        
        self.weights_1_2 = np.random.normal(0.0, self.output_nodes**-0.5, (self.hidden_nodes, self.output_nodes))
        
        self.lr = learning_rate
        
        self.layer_0 = np.zeros((1, input_nodes))
        self.hidden_layer = np.zeros((1, self.hidden_nodes))
        
    def update_input_data(self, review):
        self.layer_0 *= 0 
        #self.layer_0_idx = []
        
        for word in review.split(' '):
            if (word in self.word2index.keys()):
                self.layer_0[0][self.word2index[word]] = 1  ### Modify to reduce noise in Input data
                #self.layer_0_idx.append(self.word2index[word])
                
    def get_target_for_label(self, label):
        if label == 'POSITIVE':
            return 1
        else:
            return 0
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def sigmoid_output_2_derivative(self, output):
        return output * (1 - output)
    
    def train(self, training_reviews_raw, training_labels):
        training_reviews = list()
        for review in training_reviews_raw:
            indices = set()
            for word in review.split(' '):
                indices.add(self.word2index[word])
            training_reviews.append(list(indices))
        
        assert(len(training_reviews) == len(training_labels))
        
        correct_so_far = 0
        
        start = time.time()
        
        for i in range(len(training_reviews)):
            review = training_reviews[i]
            label = training_labels[i]
            
            ### Implement the forward pass here ###
            ## Forward pass
            
            # Input layer
               
            # Hidden layer
            self.hidden_layer *= 0
            for index in review:
                self.hidden_layer += self.weights_0_1[index]
                        
            # Output layer
            output = self.sigmoid(np.dot(self.hidden_layer, self.weights_1_2))
            
            ### Implement the backward pass here ###
            ## Backward pass
            
            # Output Error
            output_error = self.get_target_for_label(label) - output
            output_error_d = output_error*self.sigmoid_output_2_derivative(output)
            
            # Backpropagated Error
            hidden_error = np.dot(output_error_d, self.weights_1_2.T)
            hidden_error_d = hidden_error
            
            # Updates the weights
            self.weights_1_2 += self.lr*np.dot(self.hidden_layer.T, output_error_d)
            
            for idx in review:
                self.weights_0_1[idx] += self.lr*hidden_error_d[0]
            
            if np.abs(output_error) < 0.5:
                correct_so_far += 1
            
            review_per_second = i / float(time.time() - start)

            sys.stdout.write('\rProcess:' + str(100*i/float(len(training_reviews)))[:4] + \
                             '% Speed(reviews/sec):' + str(review_per_second)[:5] + \
                            '% #Correct:' + str(correct_so_far) + ' #Trained:' + str(i+1) \
                            + ' Training Accuracy:' + str(correct_so_far*100/float(i+1))[:4])
            if i % 2500 == 0:
                print(" ")
                
    def test(self, testing_reviews, testing_labels):
        correct = 0
        
        start = time.time()
        
        for i in range(len(testing_reviews)):
            pred = self.run(testing_reviews[i])
            if (pred == testing_labels[i]):
                correct += 1
                
            review_per_second = i / float(time.time() - start)
            
            sys.stdout.write('\rProcess:' + str(100*i/float(len(testing_reviews)))[:4] + \
                             '% Speed(reviews/sec):' + str(review_per_second)[:5] + \
                            '% #Correct:' + str(correct) + ' #Tested:' + str(i+1) \
                            + ' Testing Accuracy:' + str(correct*100/float(i+1))[:4])
            
        
    def run(self, review):
        # Input layer
              
        # Hidden layer
        self.hidden_layer *= 0
        unique_indices = set()
        for word in review.lower().split(' '):
            if word in self.word2index.keys():
                unique_indices.add(self.word2index[word])
        for idx in unique_indices:
            self.hidden_layer += self.weights_0_1[idx]
        
        # Output layer
        output = self.sigmoid(np.dot(self.hidden_layer, self.weights_1_2))
        
        if output[0] > 0.5:
            return 'POSITIVE'
        else:
            return 'NEGATIVE'
                

In [47]:
mlp_3 = SentimentNetwork_3(reviews[:-1000], labels[:-1000], learning_rate=0.01)

In [48]:
mlp_3.train(reviews[:-1000], labels[:-1000])

Process:0.0% Speed(reviews/sec):0.0% #Correct:0 #Trained:1 Training Accuracy:0.0 
Process:10.4% Speed(reviews/sec):1609.% #Correct:1961 #Trained:2501 Training Accuracy:78.4 
Process:20.8% Speed(reviews/sec):1470.% #Correct:4001 #Trained:5001 Training Accuracy:80.0 
Process:31.2% Speed(reviews/sec):1555.% #Correct:6119 #Trained:7501 Training Accuracy:81.5 
Process:41.6% Speed(reviews/sec):1596.% #Correct:8270 #Trained:10001 Training Accuracy:82.6 
Process:52.0% Speed(reviews/sec):1640.% #Correct:10430 #Trained:12501 Training Accuracy:83.4 
Process:62.5% Speed(reviews/sec):1676.% #Correct:12564 #Trained:15001 Training Accuracy:83.7 
Process:72.9% Speed(reviews/sec):1685.% #Correct:14669 #Trained:17501 Training Accuracy:83.8 
Process:83.3% Speed(reviews/sec):1700.% #Correct:16832 #Trained:20001 Training Accuracy:84.1 
Process:93.7% Speed(reviews/sec):1682.% #Correct:19014 #Trained:22501 Training Accuracy:84.5 
Process:99.9% Speed(reviews/sec):1677.% #Correct:20334 #Trained:24000 Training 

In [49]:
mlp_3.test(reviews[-1000:], labels[-1000:])

Process:99.9% Speed(reviews/sec):1975.% #Correct:856 #Tested:1000 Testing Accuracy:85.6

In [50]:
mlp_3.weights_0_1[0]

array([ 0.00471723, -0.00177659, -0.00153385, -0.00311599,  0.00251322,
       -0.00668386,  0.00506708, -0.00221061,  0.00092652, -0.00072419])

In [51]:
mlp_3.weights_1_2

array([[ 1.56380525],
       [-0.58895596],
       [-0.50848654],
       [-1.03297858],
       [ 0.83315348],
       [-2.21575927],
       [ 1.67978181],
       [-0.73283636],
       [ 0.30714836],
       [-0.24007622]])

# Project_7. Further Noise Reduction

In [52]:
# words most frequently seen in a review with a 'POSITIVE' label.
pos_neg_ratios.most_common()

[('edie', 4.6913478822291435),
 ('paulie', 4.0775374439057197),
 ('felix', 3.1527360223636558),
 ('polanski', 2.8233610476132043),
 ('matthau', 2.8067217286092401),
 ('victoria', 2.6810215287142909),
 ('mildred', 2.6026896854443837),
 ('gandhi', 2.5389738710582761),
 ('flawless', 2.451005098112319),
 ('superbly', 2.2600254785752498),
 ('perfection', 2.1594842493533721),
 ('astaire', 2.1400661634962708),
 ('captures', 2.0386195471595809),
 ('voight', 2.0301704926730531),
 ('wonderfully', 2.0218960560332353),
 ('powell', 1.9783454248084671),
 ('brosnan', 1.9547990964725592),
 ('lily', 1.9203768470501485),
 ('bakshi', 1.9029851043382795),
 ('lincoln', 1.9014583864844796),
 ('refreshing', 1.8551812956655511),
 ('breathtaking', 1.8481124057791867),
 ('bourne', 1.8478489358790986),
 ('lemmon', 1.8458266904983307),
 ('delightful', 1.8002701588959635),
 ('flynn', 1.7996646487351682),
 ('andrews', 1.7764919970972666),
 ('homer', 1.7692866133759964),
 ('beautifully', 1.7626953362841438),
 ('socc

In [53]:
# words most frequently seen in a review with a 'NEGATIVE' label.
list(reversed(pos_neg_ratios.most_common()))[:30]

[('boll', -4.0778152602708904),
 ('uwe', -3.9218753018711578),
 ('seagal', -3.3202501058581921),
 ('unwatchable', -3.0269848170580955),
 ('stinker', -2.9876839403711624),
 ('mst', -2.7753833211707968),
 ('incoherent', -2.7641396677532537),
 ('unfunny', -2.5545257844967644),
 ('waste', -2.4907515123361046),
 ('blah', -2.4475792789485005),
 ('horrid', -2.3715779644809971),
 ('pointless', -2.3451073877136341),
 ('atrocious', -2.3187369339642556),
 ('redeeming', -2.2667790015910296),
 ('prom', -2.2601040980178784),
 ('drivel', -2.2476029585766928),
 ('lousy', -2.2118080125207054),
 ('worst', -2.1930856334332267),
 ('laughable', -2.172468615469592),
 ('awful', -2.1385076866397488),
 ('poorly', -2.1326133844207011),
 ('wasting', -2.1178155545614512),
 ('remotely', -2.111046881095167),
 ('existent', -2.0024805005437076),
 ('boredom', -1.9241486572738005),
 ('miserably', -1.9216610938019989),
 ('sucks', -1.9166645809588516),
 ('uninspired', -1.9131499212248517),
 ('lame', -1.9117232884159072),

In [54]:
from bokeh.models import ColumnDataSource, LabelSet
from bokeh.plotting import figure, show, output_file
from bokeh.io import output_notebook
output_notebook()

Loading BokehJS ...

In [55]:
hist, edges = np.histogram(list(map(lambda x:x[1],pos_neg_ratios.most_common())), density=True, bins=100, normed=True)

p = figure(tools="pan,wheel_zoom,reset,save",
           toolbar_location="above",
           title="Word Positive/Negative Affinity Distribution")
p.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:], line_color="#555555")
show(p)

In [56]:
frequency_frequency = Counter()

for word, cnt in total_counts.most_common():
    frequency_frequency[cnt] += 1

In [58]:
hist, edges = np.histogram(list(map(lambda x:x[1],frequency_frequency.most_common())), density=True, bins=100, normed=True)

p = figure(tools="pan,wheel_zoom,reset,save",
           toolbar_location="above",
           title="The frequency distribution of the words in our corpus")
p.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:], line_color="#555555")
show(p)

# Reducing Noise by Strategically Reducing the Vocabulary

In [59]:
import sys
import time
import numpy as np

class SentimentNetwork_4:
    def __init__(self, reviews, labels, polarity_cutoff = 0.1, min_count=10, hidden_nodes = 10, learning_rate = 0.1):
        
        # set our random number generator
        np.random.seed(1)
        
        self.pre_process_data(reviews, polarity_cutoff, min_count)
        self.init_network(len(self.review_vocab), hidden_nodes, 1, learning_rate)
        
    def pre_process_data(self, reviews, polarity_cutoff, min_count):
        positive_counts = Counter()
        negative_counts = Counter()
        total_counts = Counter()
        
        for i in range(len(reviews)):
            if labels[i] == 'POSITIVE':
                for word in reviews[i].split(' '):
                    positive_counts[word] += 1
                    total_counts[word] += 1
            else:
                for word in reviews[i].split(' '):
                    negative_counts[word] += 1
                    total_counts[word] += 1
        
        pos_neg_ratios = Counter()
        
        for term, cnt in list(total_counts.most_common()):
            if cnt >= 50 :
                pos_neg_ratio = positive_counts[term]/float(negative_counts[word] + 1)
                pos_neg_ratios[term] = pos_neg_ratio
                
        for word, ratio in pos_neg_ratios.most_common():
            if ratio > 1:
                pos_neg_ratios[word] = np.log(ratio)
            else:
                pos_neg_ratios[word] = -np.log((1/(ratio + 0.01)))
        
        review_vocab = set()
        for review in reviews:
            for word in review.split(' '):
                if (total_counts[word] > min_count):
                    if (word in pos_neg_ratios.keys()):
                        if ((pos_neg_ratios[word] >= polarity_cutoff) or (pos_neg_ratios[word] <= -polarity_cutoff)):
                            review_vocab.add(word)
                    else:
                        review_vocab.add(word)
        self.review_vocab = list(review_vocab)
        
        self.word2index = {}
        for idx, word in enumerate(review_vocab):
            self.word2index[word] = idx

    def init_network(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        # Set number of nodes in input, hidden, and output layers.
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes
        
        # Initialize the weights
        self.weights_0_1 = np.zeros((self.input_nodes, self.hidden_nodes))
        
        self.weights_1_2 = np.random.normal(0.0, self.output_nodes**-0.5, (self.hidden_nodes, self.output_nodes))
        
        self.lr = learning_rate
        
        self.layer_0 = np.zeros((1, input_nodes))
        self.hidden_layer = np.zeros((1, self.hidden_nodes))
        
    def update_input_data(self, review):
        self.layer_0 *= 0 
        #self.layer_0_idx = []
        
        for word in review.split(' '):
            if (word in self.word2index.keys()):
                self.layer_0[0][self.word2index[word]] = 1  ### Modify to reduce noise in Input data
                #self.layer_0_idx.append(self.word2index[word])
                
    def get_target_for_label(self, label):
        if label == 'POSITIVE':
            return 1
        else:
            return 0
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def sigmoid_output_2_derivative(self, output):
        return output * (1 - output)
    
    def train(self, training_reviews_raw, training_labels):
        training_reviews = list()
        for review in training_reviews_raw:
            indices = set()
            for word in review.split(' '):
                if (word in self.word2index.keys()):
                    indices.add(self.word2index[word])
            training_reviews.append(list(indices))
        
        assert(len(training_reviews) == len(training_labels))
        
        correct_so_far = 0
        
        start = time.time()
        
        for i in range(len(training_reviews)):
            review = training_reviews[i]
            label = training_labels[i]
            
            ### Implement the forward pass here ###
            ## Forward pass
            
            # Input layer
               
            # Hidden layer
            self.hidden_layer *= 0
            for index in review:
                self.hidden_layer += self.weights_0_1[index]
                        
            # Output layer
            output = self.sigmoid(np.dot(self.hidden_layer, self.weights_1_2))
            
            ### Implement the backward pass here ###
            ## Backward pass
            
            # Output Error
            output_error = self.get_target_for_label(label) - output
            output_error_d = output_error*self.sigmoid_output_2_derivative(output)
            
            # Backpropagated Error
            hidden_error = np.dot(output_error_d, self.weights_1_2.T)
            hidden_error_d = hidden_error
            
            # Updates the weights
            self.weights_1_2 += self.lr*np.dot(self.hidden_layer.T, output_error_d)
            
            for idx in review:
                self.weights_0_1[idx] += self.lr*hidden_error_d[0]
            
            if np.abs(output_error) < 0.5:
                correct_so_far += 1
            
            review_per_second = i / float(time.time() - start)

            sys.stdout.write('\rProcess:' + str(100*i/float(len(training_reviews)))[:4] + \
                             '% Speed(reviews/sec):' + str(review_per_second)[:5] + \
                            '% #Correct:' + str(correct_so_far) + ' #Trained:' + str(i+1) \
                            + ' Training Accuracy:' + str(correct_so_far*100/float(i+1))[:4])
                           
    def test(self, testing_reviews, testing_labels):
        correct = 0
        
        start = time.time()
        
        for i in range(len(testing_reviews)):
            pred = self.run(testing_reviews[i])
            if (pred == testing_labels[i]):
                correct += 1
                
            review_per_second = i / float(time.time() - start)
            
            sys.stdout.write('\rProcess:' + str(100*i/float(len(testing_reviews)))[:4] + \
                             '% Speed(reviews/sec):' + str(review_per_second)[:5] + \
                            '% #Correct:' + str(correct) + ' #Tested:' + str(i+1) \
                            + ' Testing Accuracy:' + str(correct*100/float(i+1))[:4])
            
        
    def run(self, review):
        # Input layer
              
        # Hidden layer
        self.hidden_layer *= 0
        unique_indices = set()
        for word in review.lower().split(' '):
            if word in self.word2index.keys():
                unique_indices.add(self.word2index[word])
        for idx in unique_indices:
            self.hidden_layer += self.weights_0_1[idx]
        
        # Output layer
        output = self.sigmoid(np.dot(self.hidden_layer, self.weights_1_2))
        
        if output[0] > 0.5:
            return 'POSITIVE'
        else:
            return 'NEGATIVE'
                

In [60]:
mlp_4 = SentimentNetwork_4(reviews[:-1000], labels[:-1000], polarity_cutoff=0.05, min_count=20, learning_rate= 0.01)

In [61]:
mlp_4.train(reviews[:-1000], labels[:-1000])

Process:99.9% Speed(reviews/sec):1749.% #Correct:20332 #Trained:24000 Training Accuracy:84.7

In [62]:
mlp_4 = SentimentNetwork_4(reviews[:-1000], labels[:-1000], polarity_cutoff=0.8, min_count=20, learning_rate= 0.01)

In [63]:
mlp_4.train(reviews[:-1000], labels[:-1000])

Process:99.9% Speed(reviews/sec):1784.% #Correct:20332 #Trained:24000 Training Accuracy:84.7

In [64]:
mlp_4.test(reviews[-1000:], labels[-1000:])

Process:99.9% Speed(reviews/sec):1799.% #Correct:859 #Tested:1000 Testing Accuracy:85.9

In [77]:
for mlp in list((mlp_1, mlp_2, mlp_3, mlp_4)):
    print(mlp.weights_0_1[0])

[ 0.02683704 -0.01010729 -0.00872633 -0.01772733  0.01429805 -0.03802546
  0.02882736 -0.01257648  0.00527109 -0.00412004]
[ 0.00341835 -0.00128741 -0.00111151 -0.00225801  0.0018212  -0.00484347
  0.00367186 -0.00160192  0.0006714  -0.00052479]
[ 0.00471723 -0.00177659 -0.00153385 -0.00311599  0.00251322 -0.00668386
  0.00506708 -0.00221061  0.00092652 -0.00072419]
[ 0.0035733  -0.00134577 -0.00116189 -0.00236036  0.00190376 -0.00506302
  0.00383831 -0.00167453  0.00070183 -0.00054857]


In [80]:
for mlp in (mlp_1, mlp_2, mlp_3, mlp_4):
    print(mlp.weights_1_2.T)

[[ 1.60934599 -0.60610739 -0.52329456 -1.06306072  0.85741636 -2.28028605
   1.72869999 -0.75417784  0.31609306 -0.24706766]]
[[ 0.47427975 -0.17862192 -0.15421669 -0.31328762  0.25268353 -0.67200808
   0.50945379 -0.22225878  0.0931537  -0.07281168]]
[[ 1.56380525 -0.58895596 -0.50848654 -1.03297858  0.83315348 -2.21575927
   1.67978181 -0.73283636  0.30714836 -0.24007622]]
[[ 1.56328948 -0.58876172 -0.50831883 -1.03263788  0.83287869 -2.21502847
   1.67922779 -0.73259466  0.30704706 -0.23999704]]


# Project_8. What's going on in the weights.

In [82]:
mlp_full = SentimentNetwork_4(reviews[:-1000],labels[:-1000],min_count=0,polarity_cutoff=0,learning_rate=0.01)

In [83]:
mlp_full.train(reviews[:-1000],labels[:-1000])

Process:99.9% Speed(reviews/sec):1555.% #Correct:20334 #Trained:24000 Training Accuracy:84.7

In [84]:
mlp_full.weights_0_1.shape

(72810, 10)

In [85]:
np.dot(mlp_full.weights_0_1[4], mlp_full.weights_0_1[15])
# np.dot 에서 어떻게 하나의 스칼라값이 나오지? 그리고 dimension이 안맞는데 어떻게 dot production을 했을까?
# 아니다. weight_0_1[row]는 vector다. 그래서 vector끼리 dot product해서 scalar값이 나왔다. ^^

-1.1526156913637911e-10

In [93]:
mlp_full.weights_0_1[4]

array([ 0.00109032, -0.00041063, -0.00035453, -0.00072022,  0.00058089,
       -0.00154488,  0.00117118, -0.00051095,  0.00021415, -0.00016739])

In [90]:
def get_most_similar_words(focus='excellent'):
    most_similar = Counter()
    
    for word in mlp_full.word2index.keys():
        most_similar[word] = np.dot(mlp_full.weights_0_1[mlp_full.word2index[word]], mlp_full.weights_0_1[mlp_full.word2index[focus]])
                                                                                                                  
    return most_similar.most_common()

In [92]:
get_most_similar_words('excellent')

[('excellent', 0.13672950757352467),
 ('perfect', 0.12548286087225943),
 ('amazing', 0.091827633925999699),
 ('today', 0.090223662694414217),
 ('wonderful', 0.089355976962214603),
 ('fun', 0.087504466674206846),
 ('great', 0.087141758882292031),
 ('best', 0.085810885617880597),
 ('liked', 0.077697629123843398),
 ('definitely', 0.076628781406966009),
 ('brilliant', 0.073423858769279052),
 ('loved', 0.073285428928122121),
 ('favorite', 0.072781136036160751),
 ('superb', 0.071736207178505068),
 ('fantastic', 0.070922191916266197),
 ('job', 0.069160617207634029),
 ('incredible', 0.066424077952614416),
 ('enjoyable', 0.065632560502888806),
 ('rare', 0.064819212662615075),
 ('highly', 0.063889453350970515),
 ('enjoyed', 0.062127546101812953),
 ('wonderfully', 0.062055178604090148),
 ('perfectly', 0.06109320881188738),
 ('fascinating', 0.060663547937493859),
 ('bit', 0.059655427045653041),
 ('gem', 0.059510859296156758),
 ('outstanding', 0.058860808147083006),
 ('beautiful', 0.058613934703162

In [94]:
get_most_similar_words('terrible')

[('worst', 0.1696610725904984),
 ('awful', 0.12026847019691241),
 ('waste', 0.11945367265311004),
 ('poor', 0.09275888757443547),
 ('terrible', 0.0914253871977279),
 ('dull', 0.084209271678223577),
 ('poorly', 0.081241544516042014),
 ('disappointment', 0.080064759621368678),
 ('fails', 0.078599773723337513),
 ('disappointing', 0.07733948548032335),
 ('boring', 0.077127858748012867),
 ('unfortunately', 0.075502449705859079),
 ('worse', 0.070601835364194662),
 ('mess', 0.070564299623590385),
 ('stupid', 0.069484822832543022),
 ('badly', 0.066888903666228558),
 ('annoying', 0.065687021903374138),
 ('bad', 0.063093814537572152),
 ('save', 0.062880597495865734),
 ('disappointed', 0.06269235381207286),
 ('wasted', 0.061387183028051275),
 ('supposed', 0.060985452957725159),
 ('horrible', 0.060121772339380104),
 ('laughable', 0.058698406285467637),
 ('crap', 0.058104528667884549),
 ('basically', 0.057218840369636148),
 ('nothing', 0.057158220043034176),
 ('ridiculous', 0.056905481068931417),
 

In [98]:
import matplotlib.colors as colors

words_to_visualize = list()
for word, ratio in pos_neg_ratios.most_common(500):
    if(word in mlp_full.word2index.keys()):
        words_to_visualize.append(word)
    
for word, ratio in list(reversed(pos_neg_ratios.most_common()))[0:500]:
    if(word in mlp_full.word2index.keys()):
        words_to_visualize.append(word)

In [99]:
pos = 0
neg = 0

colors_list = list()
vectors_list = list()
for word in words_to_visualize:
    if word in pos_neg_ratios.keys():
        vectors_list.append(mlp_full.weights_0_1[mlp_full.word2index[word]])
        if(pos_neg_ratios[word] > 0):
            pos+=1
            colors_list.append("#00ff00")
        else:
            neg+=1
            colors_list.append("#000000")
    

In [100]:
from sklearn.manifold import TSNE
tsne = TSNE(n_components=2, random_state=0)
words_top_ted_tsne = tsne.fit_transform(vectors_list)

In [103]:
p = figure(tools="pan,wheel_zoom,reset,save",
           toolbar_location="above",
           title="vector T-SNE for most polarized words")

source = ColumnDataSource(data=dict(x1=words_top_ted_tsne[:,0],
                                    x2=words_top_ted_tsne[:,1],
                                    names=words_to_visualize))

p.scatter(x="x1", y="x2", size=8, source=source,color=colors_list)

word_labels = LabelSet(x="x1", y="x2", text="names", y_offset=6,
                  text_font_size="8pt", text_color="#555555",
                  source=source, text_align='center')
p.add_layout(word_labels)

show(p)

# green indicates positive words, black indicates negative words

/home/jinsangjeong/anaconda3/envs/dlnd/lib/python3.6/site-packages/bokeh/util/deprecation.py:34: BokehDeprecationWarning: 
Supplying a user-defined data source AND iterable values to glyph methods is deprecated.

See https://github.com/bokeh/bokeh/issues/2056 for more information.

  warn(message)
/home/jinsangjeong/anaconda3/envs/dlnd/lib/python3.6/site-packages/bokeh/util/deprecation.py:34: BokehDeprecationWarning: 
Supplying a user-defined data source AND iterable values to glyph methods is deprecated.

See https://github.com/bokeh/bokeh/issues/2056 for more information.

  warn(message)
